name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    environment: 'Test CI'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=2.1.1 python3 -

      - name: Set up Python and Poetry
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.11
          cache: poetry
      - run: poetry install --all-extras

      - name: Run tests and generate coverage report
        run: |
          poetry run pytest --cov=biochatter --cov-report=xml tests
          poetry run coverage report
        shell: bash

      - name: Generate coverage badge
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.base_ref == 'refs/heads/main' && github.event.pull_request.merged == true)
        run: |
          poetry run coverage-badge -f -o docs/coverage/coverage.svg
        shell: bash

      - name: Commit changes
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.base_ref == 'refs/heads/main' && github.event.pull_request.merged == true)
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: coverage
          FOLDER: docs/coverage
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}